### PR TITLE
ui: collapse and expand files

### PR DESCRIPTION
**Pull request by tanyunshi**
Refers to https://github.com/etsy/hound/issues/182, https://github.com/etsy/hound/pull/235 and https://github.com/etsy/hound/issues/201: New feature for search quick navigation.

 - Click on the button [expand all] or [collapse all] to expand/collapse all
 - Click on a repository title to expand/collapse all the files of the repo
 - Click on a file title to expand/collapse the file content

demo

### CODE REVIEW

**Comment by rbarrois** [comment]
I don't see any tests for this; are there some upstream tests we could expand?

**Comment by tanyunshi** [comment]
You are right, I will add some tests. Good opportunity to write my first GO hello world  :D

**Comment by tanyunshi** [comment]
@rbarrois  Actually there are tests for the backend implementation, not for UI. I think it's a large amount of work to create UI tests (e.g., shall we begin by choosing a test framework, etc ?). :-[
 
Personally I prefer to test the new feature in use: it does help us in code refactoring. :)

**Comment by rbarrois** [comment]
@tanyunshi OK :)

**Comment by tanyunshi** [comment]
merged 0cc746b

**Pull request closed without merging**
